#!/bin/sh
set -eu

project_dir="$(cd "$(dirname "$0")/.." && pwd)"
output="$project_dir/ios/Flutter/LocalSigning.xcconfig"

if ! command -v security >/dev/null 2>&1; then
  exit 0
fi

identity="$(
  security find-identity -v -p codesigning 2>/dev/null \
    | sed -n 's/.*"Apple Development: .* (\([A-Z0-9][A-Z0-9]*\))".*/\1/p' \
    | head -n 1
)"

if [ -z "$identity" ]; then
  exit 0
fi

tmp="${output}.tmp"
{
  echo "// Generated by scripts/configure-ios-local-signing.sh."
  echo "// This file is ignored by git and only affects local Debug builds."
  echo "DEVELOPMENT_TEAM = $identity"
  echo "CODE_SIGN_STYLE = Automatic"
  echo "CODE_SIGN_IDENTITY = Apple Development"
} > "$tmp"
mv "$tmp" "$output"

echo "Using local iOS development team: $identity"
